import Head from "next/head";
import { CartItems, CartTotals } from "src/features/cart-items";
import { fetchCartItems } from "src/features/cart-items/api/fetchCartItems";
import { DeliveryOptions } from "src/features/delivery-options";
import { PageStepper } from "src/features/page-stepper";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageStepper activeStep={1} />

      <CartItems />
      <CartTotals />
      <DeliveryOptions />
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      initializeStore: {
        cartItems: await fetchCartItems(),
      },
    },
  };
}
