import Head from "next/head";
import Image from "next/image";
import { CartItems } from "src/features/cart-items/CartItems";
import { DeliveryAddress } from "src/features/delivery-address/DeliveryAddress";
import { PersonalDetails } from "src/features/personal-details/PersonalDetails";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CartItems />
        <PersonalDetails />
        <DeliveryAddress />
      </main>
    </div>
  );
}
