import Head from "next/head";
import { CartItems } from "src/features/cart-items/CartItems";
import { PersonalDetails } from "src/features/personal-details/PersonalDetails";

export default function Home(props: any) {
  return (
    <div>
      <Head>
        <title>Next Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CartItems />
        <PersonalDetails />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(
    "https://fakestoreapi.com/products?limit=3"
  ).then((res) => res.json());

  const mapResponse = response.map((cartItem: any) => ({
    price: cartItem.price,
    title: cartItem.title,
    qty: 3,
  }));

  return {
    props: {
      initializeStore: {
        cartItems: mapResponse,
      },
    },
  };
}
