import Head from "next/head";
import Image from "next/image";
import { DeliveryAddress } from "../src/features/DeliveryAddress/DeliveryAddress";
import { PersonalDetails } from "../src/features/PersonalDetails/PersonalDetails";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PersonalDetails />
        <DeliveryAddress />
      </main>
    </div>
  );
}
